stages:
  - build
  - deploy

build-image:
  stage: build

  when: manual

  image: docker:20.10.16
  services:
    - docker:28.1.1-dind-rootless
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - APP_VERSION=`cat Cargo.toml | grep "version = " | head -1 | cut -d "=" -f2 | tr -d '"' | tr -d ' '`
    - "echo $APP_VERSION > version"
    - DOCKER_IMAGE=$CI_REGISTRY_IMAGE:$APP_VERSION
    - docker build --progress=plain -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
    - DOCKER_DEV_IMAGE=$CI_REGISTRY_IMAGE:dev
    - docker tag $DOCKER_IMAGE $DOCKER_DEV_IMAGE
    - docker push $DOCKER_DEV_IMAGE

  artifacts:
    paths:
      - version

  tags:
    - rust

deploy-dev:
  stage: deploy

  needs:
    - build-image

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - cd /opt/myapp
    - docker compose down
    - docker compose pull
    - docker compose up -d

  tags:
    - tinybull
