stages:
  - build
  - security

variables:
  IMAGE_NAME: tinyops/shortly
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build

  when: manual

  image: docker:29.4.0-cli-alpine3.23

  cache:
    paths:
      - frontend/node_modules/
      - target/

  services:
    - name: docker:29.4.0-dind-alpine3.23
      alias: docker

  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN

  script:
    - APP_VERSION=`cat Cargo.toml | grep "version = " | head -1 | cut -d "=" -f2 | tr -d '"' | tr -d ' '`
    - echo "APP_VERSION=$APP_VERSION" > build.env
    - DOCKER_IMAGE=$IMAGE_NAME:$APP_VERSION
    - docker build --progress=plain --platform=linux/amd64 -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

  artifacts:
    reports:
      dotenv: build.env
    expire_in: 1 hour

check-cve:
  stage: security

  allow_failure: true

  needs:
    - build

  image:
    name: aquasec/trivy:0.70.0
    entrypoint: [""]

  before_script:
    - export TRIVY_USERNAME="$DOCKER_HUB_USER"
    - export TRIVY_PASSWORD="$DOCKER_HUB_TOKEN"

  script:
    - trivy image --disable-telemetry -s HIGH,CRITICAL --exit-code 1 $IMAGE_NAME:$APP_VERSION
