stages:
  - build
  - security
  - deploy

variables:
  IMAGE_NAME: tinyops/shortly
  DOCKER_TLS_CERTDIR: ""

build-image:
  stage: build

  when: manual

  image: docker:29.0.1

  cache:
    paths:
      - frontend/node_modules/
      - target/

  services:
    - name: docker:29.0.1-dind-alpine3.22
      alias: docker

  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN

  script:
    - APP_VERSION=`cat Cargo.toml | grep "version = " | head -1 | cut -d "=" -f2 | tr -d '"' | tr -d ' '`
    - "echo $APP_VERSION > version"
    - DOCKER_IMAGE=$IMAGE_NAME:$APP_VERSION
    - docker build --progress=plain --platform=linux/amd64 -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

  artifacts:
    paths:
      - version
    expire_in: 1 hour

check-cve:
  stage: security

  allow_failure: true

  needs:
    - build-image

  image:
    name: aquasec/trivy:latest
    entrypoint: [""]

  before_script:
    - export IMAGE_TAG=$(cat version)
    - export TRIVY_USERNAME="$DOCKER_HUB_USER"
    - export TRIVY_PASSWORD="$DOCKER_HUB_TOKEN"

  script:
    - trivy image --disable-telemetry -s HIGH,CRITICAL --exit-code 1 $IMAGE_NAME:$IMAGE_TAG

deploy-dev:
  stage: deploy

  needs:
    - build-image

  before_script:
    - export IMAGE_TAG=$(cat version)
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN

  script:
    - echo "Deploying version $APP_VERSION"
    - yq -yi '.services.app.image = "'$IMAGE_NAME':'$IMAGE_TAG'"' /opt/shortly/docker-compose.yml
    - cd /opt/shortly
    - docker compose down
    - docker compose pull
    - docker compose up -d

  tags:
    - tinybull
