bind: "0.0.0.0:8080"

log-level: debug
log-target: console

db-cnn: "sqlite://./data/app.db?mode=rwc"

base-url: "http://localhost:8080"

features:
  create-url:
    enabled: true
    auth-only: true

auth:
  enabled: true
  type: gitlab
  providers:
    gitlab:
      base-url: https://gitlab.com
      application-id: test-app-id
      secret: test-secret

short-url:
  ttl: 168
  max-length: 2048

scheduler:
  cleanup-expired-urls: "0 0 * * *"
