apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-chart.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- if .Values.config.nginx.enabled }}
        - name: nginx
          image: "{{ .Values.config.nginx.image.repository }}:{{ .Values.config.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.config.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.nginx.port }}
              protocol: TCP
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
          {{- with .Values.config.nginx.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.nginx.startupProbe.enabled }}
          startupProbe:
            {{- if .Values.probes.nginx.startupProbe.httpGet }}
            httpGet:
              {{- toYaml .Values.probes.nginx.startupProbe.httpGet | nindent 14 }}
            {{- else if .Values.probes.nginx.startupProbe.tcpSocket }}
            tcpSocket:
              {{- toYaml .Values.probes.nginx.startupProbe.tcpSocket | nindent 14 }}
            {{- end }}
            initialDelaySeconds: {{ .Values.probes.nginx.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.nginx.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.nginx.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.probes.nginx.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.probes.nginx.startupProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.nginx.livenessProbe.enabled }}
          livenessProbe:
            {{- if .Values.probes.nginx.livenessProbe.httpGet }}
            httpGet:
              {{- toYaml .Values.probes.nginx.livenessProbe.httpGet | nindent 14 }}
            {{- else if .Values.probes.nginx.livenessProbe.tcpSocket }}
            tcpSocket:
              {{- toYaml .Values.probes.nginx.livenessProbe.tcpSocket | nindent 14 }}
            {{- end }}
            initialDelaySeconds: {{ .Values.probes.nginx.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.nginx.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.nginx.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.probes.nginx.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.probes.nginx.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.nginx.readinessProbe.enabled }}
          readinessProbe:
            {{- if .Values.probes.nginx.readinessProbe.httpGet }}
            httpGet:
              {{- toYaml .Values.probes.nginx.readinessProbe.httpGet | nindent 14 }}
            {{- else if .Values.probes.nginx.readinessProbe.tcpSocket }}
            tcpSocket:
              {{- toYaml .Values.probes.nginx.readinessProbe.tcpSocket | nindent 14 }}
            {{- end }}
            initialDelaySeconds: {{ .Values.probes.nginx.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.nginx.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.nginx.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.probes.nginx.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.probes.nginx.readinessProbe.failureThreshold }}
          {{- end }}
        {{- end }}
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- if .Values.config.nginx.enabled }}
            - name: backend
              containerPort: {{ .Values.config.nginx.backendPort }}
              protocol: TCP
            {{- else }}
            - name: http
              containerPort: 8080
              protocol: TCP
            {{- end }}
          envFrom:
          - configMapRef:
              name: {{ include "helm-chart.fullname" . }}
          - secretRef:
              name: {{ include "helm-chart.fullname" . }}
          {{- if .Values.probes.shortly.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.probes.shortly.startupProbe.httpGet.path }}
              {{- if .Values.config.nginx.enabled }}
              port: backend
              {{- else }}
              port: http
              {{- end }}
            initialDelaySeconds: {{ .Values.probes.shortly.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.shortly.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.shortly.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.probes.shortly.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.probes.shortly.startupProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.shortly.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.shortly.livenessProbe.httpGet.path }}
              {{- if .Values.config.nginx.enabled }}
              port: backend
              {{- else }}
              port: http
              {{- end }}
            initialDelaySeconds: {{ .Values.probes.shortly.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.shortly.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.shortly.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.probes.shortly.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.probes.shortly.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.shortly.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.shortly.readinessProbe.httpGet.path }}
              {{- if .Values.config.nginx.enabled }}
              port: backend
              {{- else }}
              port: http
              {{- end }}
            initialDelaySeconds: {{ .Values.probes.shortly.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.shortly.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.shortly.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.probes.shortly.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.probes.shortly.readinessProbe.failureThreshold }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.persistence.enabled }}
          - name: data
            mountPath: {{ .Values.persistence.mountPath }}
            {{- if .Values.persistence.subPath }}
            subPath: {{ .Values.persistence.subPath }}
            {{- end }}
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- if .Values.config.nginx.enabled }}
      - name: nginx-config
        configMap:
          name: {{ include "helm-chart.fullname" . }}-nginx
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "helm-chart.fullname" .) }}
      {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
