apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  DB_CNN: {{ .Values.secrets.dbCnn | quote }}
  AUTH_PROVIDERS_GITLAB_APPLICATION_ID: {{ .Values.secrets.auth.providers.gitlab.applicationId | quote }}
  AUTH_PROVIDERS_GITLAB_SECRET: {{ .Values.secrets.auth.providers.gitlab.secret | quote }}
